version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - .:/app
      - /var/tmp
      - sockets:/app/tmp/sockets
    depends_on:
      - db
  nginx:
    build:
      context: ./docker/nginx
      args:
        NGINX_HOST_NAME: "localhost"
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - sockets:/app/tmp/sockets

volumes:
  sockets:
