version: "3"
services:
  db:
    image: mysql:8.0
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
  app:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - .:/app
      - /var/tmp
      - sockets:/app/tmp/sockets
    depends_on:
      - db
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    environment:
      NGINX_HOST_NAME: "localhost"
    # Using environment variables in nginx configuration
    command: >
      /bin/sh -c "envsubst '$$NGINX_HOST_NAME' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - sockets:/app/tmp/sockets

volumes:
  sockets:
