version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.9.1
  aws-ecs: circleci/aws-ecs@1.2.0
workflows:
  nginx-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          create-repo: true
          dockerfile: Dockerfile
          no-output-timeout: 20m
          path: ./docker/nginx/
          region: AWS_REGION
          repo: kaoreal-nginx
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "kaoreal-task-df"
          cluster-name: "kaoreal-cluster"
          service-name: "kaoreal-service"
          container-image-name-updates: "container=nginx,tag=${CIRCLE_SHA1}"
  rails-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_KEY
          create-repo: true
          dockerfile: ./docker/rails/Dockerfile
          no-output-timeout: 20m
          path: .
          region: AWS_REGION
          repo: kaoreal-rails
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "kaoreal-task-df"
          cluster-name: "kaoreal-cluster"
          service-name: "kaoreal-service"
          container-image-name-updates: "container=rails,tag=${CIRCLE_SHA1}"
